modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "minecraft_access"
version = "${version}"
displayName = "Minecraft Access"
authors = "Shoaib"
description = '''
A mod for minecraft java that adds accessibility feature.
'''
#logoFile = ""

[[dependencies.minecraft_access]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minecraft_access]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minecraft_access]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"