modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "minecraft_access"
version = "${version}"
displayName = "Minecraft Access"
authors = "Shoaib"
description = '''
A mod for minecraft java that adds accessibility feature.
'''
#logoFile = ""

[[dependencies.minecraft_access]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minecraft_access]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"