repositories {
    mavenCentral()
    // Make sure getting lombok jar from maven central (instead of forge repo or so)
    // ref: https://discuss.gradle.org/t/how-to-make-gradle-stop-getting-a-not-existing-jar-from-a-third-party-maven-repo/48290/4
    exclusiveContent {
        forRepository {
            mavenCentral()
        }
        filter {
            includeGroup "org.projectlombok"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'Modrinth'
                url = 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
}

architectury {
    common("fabric", "neoforge")
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation libs.fabricLoader

    modImplementation "maven.modrinth:jade:${jade_fabric_version}+fabric"

    modImplementation libs.architecturyApi

    // lombok that makes the life easier
    // https://projectlombok.org/setup/gradle
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    // dependent on log4j for dynamic changing
    implementation libs.log4jApi
    implementation libs.log4jCore

    // Unit test dependencies
    testImplementation libs.junitJupiter
    testImplementation libs.junitJupiterParams
    testImplementation libs.assertjCore
    testImplementation libs.mockitoCore
    testImplementation libs.mockitoJunitJupiter

    // benchmark dependencies
    testImplementation libs.jmhCore
    testAnnotationProcessor libs.jmhGeneratorAnnprocess
}

test {
    useJUnitPlatform()
    // Since JDK 21
    // ref: https://stackoverflow.com/questions/77951485/getting-a-java-agent-has-been-loaded-warning-in-intellij-after-upgrading-jdk-17
    jvmArgs("-XX:+EnableDynamicAgentLoading")
}
