modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "minecraft_access"
version = "${version}"
displayName = "Minecraft Access"
authors = "Shoaib, Boholder"
description = '''
A mod for minecraft java that adds accessibility feature.
'''
#logoFile = ""

[[dependencies.minecraft_access]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minecraft_access]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

#[[mixins]]
#config = "minecraft_access.mixins.json"

#[[mixins]]
#config = "minecraft_access-common.mixins.json"